apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist.fullname" . }}-config
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
data:
  USER: {{ .Values.env.user | quote }}
  MYSQL_HOST: {{ .Values.env.mysqlHost | quote }}
  MYSQL_USER: {{ .Values.env.mysqlUser | quote }}
  MYSQL_TABLE: {{ .Values.env.mysqlTable | quote }}
  MYSQL_DB: {{ .Values.env.mysqlDatabase | quote }}
  MYSQL_DATABASE: {{ .Values.env.mysqlDatabase | quote }}
  API_BASE_URL: {{ .Values.env.apiBaseUrl | quote }}
