apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todolist.fullname" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.apiPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.apiName" . }}
                port:
                  number: {{ .Values.api.service.port }}
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.frontendName" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
