nameOverride: ""
fullnameOverride: ""

secret:
  # Required at install/upgrade time. Keep empty here on purpose.
  rootPassword: ""
  # Optional. If empty, app DB password defaults to rootPassword.
  mysqlPassword: ""

env:
  user: "kadmon-omri"
  # Slide requirement: default MYSQL_HOST is backend.
  mysqlHost: "backend"
  mysqlUser: "root"
  mysqlTable: "todos"
  mysqlDatabase: "todolist"
  apiBaseUrl: "/todos"

frontend:
  replicaCount: 1
  image:
    repository: "ghcr.io/bennyro-mta/todolist-vue"
    tag: "1.2"
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: LoadBalancer
    port: 8080
  probes:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

api:
  replicaCount: 1
  image:
    repository: "ghcr.io/bennyro-mta/todos-api"
    tag: "1.2"
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: LoadBalancer
    port: 8080
  initContainer:
    image: "mariadb:10"
  probes:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

mariadb:
  replicaCount: 1
  image:
    repository: "mariadb"
    tag: "10"
    pullPolicy: IfNotPresent
  port: 3306
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
  probes:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 10
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

ingress:
  className: "nginx"
  host: "todolist.local"
  frontendPath: "/"
  apiPath: "/todos"
  annotations: {}
  tls: []
